# -*- coding: utf-8 -*-
"""get_a_melly

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Td_qfFfLbWhNA6W7XVainmrNJr7OiPkC
"""

import requests
from bs4 import BeautifulSoup

# Specify the URL
url = "https://melanzana.com/book-an-appointment/"

# Send a GET request to the URL
response = requests.get(url)

# Parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')

# Find elements with class "tooltipster"
tooltipster_elements = soup.find_all(class_="tooltipster")

found_elements = False
for element in tooltipster_elements:
    parent_div = element.find_parent("div", {"data-date": True})
    if parent_div:
        data_date = parent_div["data-date"]
        print("open appointments:", data_date)
        found_elements = True

if not found_elements:
    print("no appointments available")

print(soup.prettify())

